### PR TITLE
Fixing typos related to temperature sensor naming (temperatur, tempratur)

### PR DESCRIPTION
**Pull request by zsolth**

### CODE REVIEW

**Comment by zsolth** [comment]
Hi @frawe huge thanks for creating the integration, been looking for this for ~2 years! 

So far seems to be working nicely, I've just noticed a few typos in temperature sensor names, figure I'd fix it, that's what this PR is about. 

Please do note that I don't have a test HA environment, so I've not been able to test it, but if that helps let me know and I'll just delete your version from my instance, install mine and see if it still works...

**Comment by frawe** [comment]
Hi @zsolth great, that you like it.

Tis is my first integration.

Your change looks good, the only problem I see is that the uniq id also changes, so hass would create new sensors with it, and that would couse the loss of old data...

What do you mean, should we just do it? I think we also would need to inform the users of the intergration then...

Or should we only change the readable names ....

**Comment by zsolth** [comment]
Ah, I see, fair point. Given it's only been out for two weeks, I'd say it's better to bite the bullet now and not keep dragging the bad names on even for unique ids. With that said, it's up to you really...

**Comment by frawe** [comment]
Yes, you are right.

I will accept it, do you find other typos @zsolth  - not that I need to do that again

**Pull request merged**
